#Tomcat
server:
         tomcat:
           uri-encoding: UTF-8
           max-threads: 1000
           #最小空闲线程数量
           min-spare-threads: 30
         servlet:
           context-path: /admin
         port: 8000
#mysql
spring:
  profiles:
    active: dev
  #servlet配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    database: 0
    host: 192.168.92.114
    port: 6379
    password: #密码(默认为空)
    timeout: 6000ms #连接超时市时长(毫秒)
    #Redis连接池配置
    jedis:
      pool:
        max-active: 1000 #连接池最大连接数(使用负值表示没有限制)
        max-wait: -1ms  #连接池最大阻塞等待时间(使用负值表示没有限制)
        max-idle: 10   #连接池中的最大空闲连接
        min-idle: 5    #连接池中的最小空闲连接
  #freemarker配置
  freemarker:
    suffix: .html
    request-context-attribute: request
  #json配置时间
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #缓存配置
  cache:
    type: none
person:
    redis:
      open: false #是否开启Redis缓存， true开启  false关闭
      shiro:
        redis: false #true表示shiro  session存到Redis里，需要开启Redis，才会生效【分布式场景】
#j2cache配置
j2cache:
  config-location: /cache/j2cache-no.properties #j2cache配置文件的路径
  open-spring-cache: true   #开启spring缓存

#mybatis
mybatis-plus:
  mapper-locations:  classpath*:/mapper/**/*.xml
  #配置
  type-aliases-package: com.person.po
  global-config:
    #主键类型： 0:"数据库ID自增"，1:"用户输入ID"，2:"全局唯一ID"(数字类型唯一ID),3:"全局唯一ID UUID"
    id-type: 0
    #字段策略 0:"忽略判断"，1:"非null判断"，2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置
    db-config:
      logic-delete-value: -1
      logic-not-delete-value: 0
        #自定义填充策略接口实现
#        meta-object-handler: com.freeter.MyMetaObjectHandler
        #自定义SQL注入器
 #       sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    #下划线映射驼峰大小写
    map-underscore-to-camel-case: true
    cache-enabled: false
    #在null值上调用setter方法
    call-setters-on-nulls: true
#logging
logging:
  level: debug
  level.com.example: debug
  path: logs/
  file: admin.log

